### ISSUE TITLE
1.0.0 roadmap

### ISSUE THREAD

**Issue by petabyt** [petabyt/fudge#16]
- [x] Liveview + change camera settings
- [x] Gallery for downloaded photos in /Camera/fudge

For next major release/unnecessary for 1.0.0
- [ ] Swipe between photos (https://github.com/petabyt/fudge/issues/13)
- [ ] UPnP discovery for PC AUTO SAVE feature
- [ ] iOS port (UI, WiFi selection, downloading, sharing, etc)
- [ ] Bluetooth (I haven't decided on what library to use)

**Comment by petabyt** [comment]
Closed in favor of a private list (I don't feel like updating this)
